# Generated by Django 5.2.7 on 2025-10-23 09:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('endpoint', models.CharField(max_length=200)),
                ('requests', models.IntegerField()),
                ('success_rate', models.FloatField()),
                ('error_4xx', models.FloatField()),
                ('error_5xx', models.FloatField()),
                ('avg_response_time_ms', models.IntegerField()),
            ],
        ),
    ]
