# Generated by Django 5.2.7 on 2025-10-23 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_metric'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Metric',
        ),
    ]
