# Generated by Django 5.2.7 on 2025-10-23 13:07

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_need'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.CharField(default='Nouveau', max_length=20, validators=[tasks.models.validate_status]),
        ),
    ]
